spring.application.name=main

spring.datasource.url=jdbc:postgresql://localhost:5433/main
spring.datasource.username=postgres
spring.datasource.password=user1
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Environment variables
telegram.bot.username=${TELEGRAM_BOT_NAME:}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
proxy.host=${APP_PROXY_HOST:127.0.0.1}
proxy.port=${APP_PROXY_PORT:1080}
proxy.enabled=${APP_PROXY_ENABLED:true}
