spring.application.name=main

spring.datasource.url=jdbc:postgresql://localhost:5433/main
spring.datasource.username=postgres
spring.datasource.password=user1
spring.datasource.driver-class-name=org.postgresql.Driver

spring.threads.virtual.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB
spring.mail.host=smtp.mail.ru
spring.mail.port=465
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory

# Environment variables
telegram.bot.username=${TELEGRAM_BOT_NAME:}
telegram.bot.token=${TELEGRAM_BOT_TOKEN:}
proxy.host=${APP_PROXY_HOST:127.0.0.1}
proxy.port=${APP_PROXY_PORT:1080}
proxy.enabled=${APP_PROXY_ENABLED:true}
spring.mail.username=${EMAIL_ADDRESS:}
spring.mail.password=${EMAIL_PASSWORD:}


